pub mod error;
pub mod installer;
pub mod updater;
pub mod mcp_sync;
pub mod diagnostics;
pub mod paths;
pub mod git;
pub mod version;
pub mod manifest;
pub mod settings;
pub mod output_styles;
pub mod skills;
pub mod instructions;
pub mod mcp_config;

pub use error::{Result, RhinolabsError};
pub use installer::Installer;
pub use updater::Updater;
pub use mcp_sync::McpSync;
pub use diagnostics::Doctor;
pub use paths::Paths;
pub use version::Version;
pub use manifest::{Manifest, PluginManifest, Author};
pub use settings::{Settings, PluginSettings, PermissionConfig, StatusLineConfig, AttributionConfig};
pub use output_styles::{OutputStyles, OutputStyle};
pub use skills::{Skills, Skill, SkillCategory, CreateSkillInput, UpdateSkillInput};
pub use instructions::{InstructionsManager, Instructions};
pub use mcp_config::{McpConfigManager, McpConfig, McpServer, McpSettings};
